# Generated by Django 2.2.7 on 2020-01-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flexitimelog_logged_in_default_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexitimelog',
            options={'permissions': [('view_all_user_logs', 'Can view logs of all active users.')]},
        ),
    ]
